version: '3.8'
services:
  contact:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1001:8000
    depends_on:
      - contact_db
    volumes:
      - .:/app
  contact_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: contact
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33171:3306



